(function(){'use strict';var T=document.getElementById('terminal'),cwd='/home/user',hist=[],hi=-1,inp='',cp=0;
var FS={'/home/user':{t:'d',c:['projects','documents','.kimchirc']},'/home/user/projects':{t:'d',c:['web-app','api-server']},'/home/user/projects/web-app':{t:'d',c:['index.html','app.js','package.json']},'/home/user/projects/api-server':{t:'d',c:['server.py','requirements.txt']},'/home/user/documents':{t:'d',c:['notes.txt','todo.md']},'/home/user/.kimchirc':{t:'f',v:'# Kimchi Config\nmodel=kimchi-coder-v2\ntheme=dark'},'/home/user/projects/web-app/package.json':{t:'f',v:'{"name":"web-app","version":"1.0.0"}'},'/home/user/projects/api-server/server.py':{t:'f',v:'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello(): return "Hello!"'},'/home/user/projects/api-server/requirements.txt':{t:'f',v:'flask==3.0.0'},'/home/user/documents/notes.txt':{t:'f',v:'Update API keys'},'/home/user/documents/todo.md':{t:'f',v:'# TODO\n- [ ] New feature\n- [x] Fix bug\n- [ ] Deploy'}};
function rp(i){if(!i||i==='.')return cwd;if(i==='~')return'/home/user';if(i==='..')return cwd.split('/').slice(0,-1).join('/')||'/home/user';if(i[0]==='/')return i;return cwd+'/'+i;}
function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function pr(){return'<span class="info">'+cwd.replace('/home/user','~')+'</span> <span class="accent">$</span> ';}
function rl(h){var d=document.createElement('div');d.className='line';d.innerHTML=h;T.appendChild(d);}
function rpr(){var d=document.createElement('div');d.className='line';d.id='cp';d.innerHTML=pr()+'<span class="cursor"> </span>';T.appendChild(d);T.scrollTop=T.scrollHeight;}
function ui(){var e=document.getElementById('cp');if(!e)return;var b=inp.slice(0,cp),c=inp[cp]||' ',a=inp.slice(cp+1);e.innerHTML=pr()+esc(b)+'<span class="cursor">'+esc(c)+'</span>'+esc(a);}
var CMD={help:function(){return['<span class="accent">Commands:</span>','','  <span class="info">help</span>        Show commands','  <span class="info">kimchi</span>      Start session','  <span class="info">kimchi --plan</span> Plan mode','  <span class="info">kimchi setup</span> Setup wizard','  <span class="info">ls</span>          List files','  <span class="info">cd [dir]</span>    Change dir','  <span class="info">cat [file]</span>  Show file','  <span class="info">pwd</span>         Print dir','  <span class="info">clear</span>       Clear','  <span class="info">date</span>        Date/time','  <span class="info">/ferment</span>    Ferment workflow','  <span class="info">/help</span>       Slash cmds'].join('\n');},
kimchi:function(a){if(a[0]==='--plan')return'<span class="info">Plan mode active. Scanning... 12 files found.</span>';if(a[0]==='setup')return'<span class="info">1/3</span> Auth OK\n<span class="info">2/3</span> Model: kimchi-coder-v2\n<span class="info">3/3</span> Workspace ready\n<span class="info">Setup complete!</span>';if(a[0]==='update')return'<span class="info">v0.42.1 - up to date!</span>';if(a[0]==='--version')return'<span class="info">kimchi v0.42.1</span>';return'\n<span class="accent">  KIMCHI CODING v0.42.1</span>\n<span class="muted">  Multi-model orchestration</span>\n\n<span class="warn">  Session mode:</span>\n  [1] /ferment workflow\n  [2] Chat and code\n\n<span class="muted">  Ready. Type /help for commands.</span>\n';},
ls:function(a){var p=rp(a[0]||'.');var n=FS[p];if(!n||n.t!=='d')return'<span class="error">ls: not found</span>';return n.c.map(function(c){var x=FS[p+'/'+c];return x&&x.t==='d'?'<span class="info">'+c+'/</span>':c;}).join('  ');},
cd:function(a){if(!a[0]||a[0]==='~'){cwd='/home/user';return'';}var p=rp(a[0]);var n=FS[p];if(!n||n.t!=='d')return'<span class="error">cd: '+a[0]+': not found</span>';cwd=p;return'';},
cat:function(a){if(!a[0])return'<span class="error">cat: missing file</span>';var p=rp(a[0]);var n=FS[p];if(!n)return'<span class="error">cat: not found</span>';if(n.t==='d')return'<span class="error">cat: is directory</span>';return esc(n.v);},
pwd:function(){return cwd;},echo:function(a){return a.join(' ');},clear:function(){T.innerHTML='';return null;},date:function(){return'<span class="info">'+new Date().toString()+'</span>';},whoami:function(){return'user';},history:function(){return hist.map(function(h,i){return'  '+(i+1)+' '+h;}).join('\n')||'<span class="muted">empty</span>';}};
var SL={'/ferment':function(){return'\n<span class="accent">Ferment Workflow</span>\n\n<span class="info">Phase 1:</span> Understanding... done\n<span class="info">Phase 2:</span> Planning... 5 steps\n<span class="info">Phase 3:</span> Executing... all done\n<span class="info">Phase 4:</span> Self-eval: Grade A\n\n<span class="accent">Complete!</span> 3 files, 47 lines.\n';},'/help':function(){return'<span class="accent">Slash:</span>\n  /ferment  Autonomous workflow\n  /bug      Report bug\n  /help     This list\n  /login    Auth\n  /model    Switch model';},'/bug':function(){return'<span class="info">Bug report opened</span>';},'/login':function(){return'<span class="info">Authenticated as user@kimchi.dev</span>';},'/model':function(a){return'<span class="info">Model: '+(a[0]||'kimchi-coder-v2')+'</span>';}};
function ai(s){if(s.match(/hello|hi/i))return'<span class="accent">kimchi&gt;</span> Hey! How can I help?';if(s.match(/fix|bug/i))return'<span class="accent">kimchi&gt;</span> What file and what behavior?';if(s.match(/function|write/i))return'<span class="accent">kimchi&gt;</span>\n<span class="info">function greet(n) {\n  return `Hello ${n}!`;\n}</span>';return'<span class="accent">kimchi&gt;</span> Working on: "'+esc(s)+'"\n<span class="muted">Type help for commands</span>';}
function exec(s){var t=s.trim();if(!t)return;hist.push(t);hi=hist.length;var e=document.getElementById('cp');if(e){e.innerHTML=pr()+esc(t);e.removeAttribute('id');}
var sk=Object.keys(SL).find(function(k){return t.startsWith(k);});if(sk){var a=t.slice(sk.length).trim().split(/\s+/).filter(Boolean);var r=SL[sk](a);if(r)rl(r);rpr();return;}
var p=t.split(/\s+/),c=p[0],ar=p.slice(1);if(CMD[c]){var res=CMD[c](ar);if(res!=null&&res!=='')rl(res);}else{rl(ai(t));}rpr();}
T.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();var i=inp;inp='';cp=0;exec(i);}else if(e.key==='Backspace'){e.preventDefault();if(cp>0){inp=inp.slice(0,cp-1)+inp.slice(cp);cp--;ui();}}else if(e.key==='ArrowLeft'){e.preventDefault();if(cp>0){cp--;ui();}}else if(e.key==='ArrowRight'){e.preventDefault();if(cp<inp.length){cp++;ui();}}else if(e.key==='ArrowUp'){e.preventDefault();if(hi>0){hi--;inp=hist[hi];cp=inp.length;ui();}}else if(e.key==='ArrowDown'){e.preventDefault();if(hi<hist.length-1){hi++;inp=hist[hi];cp=inp.length;}else{hi=hist.length;inp='';cp=0;}ui();}else if(e.key==='Tab'){e.preventDefault();var m=Object.keys(CMD).concat(Object.keys(SL)).find(function(x){return x.startsWith(inp);});if(m){inp=m+' ';cp=inp.length;ui();}}else if(e.ctrlKey&&e.key==='l'){e.preventDefault();CMD.clear();rpr();}else if(e.ctrlKey&&e.key==='c'){e.preventDefault();inp='';cp=0;rpr();}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){e.preventDefault();inp=inp.slice(0,cp)+e.key+inp.slice(cp);cp++;ui();}T.scrollTop=T.scrollHeight;});
T.addEventListener('click',function(){T.focus();});
rl('<span class="accent">  KIMCHI TERMINAL v1.0.0</span>');rl('');rl('<span class="muted">  Web-based coding terminal powered by Kimchi</span>');rl('<span class="muted">  Type <span class="info">help</span> for commands, <span class="info">kimchi</span> to start</span>');rl('');rpr();T.focus();
})();
